[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.11.0"
log = "0.4.17"
env_logger = "0.10.0"
winit = "0.27"
egui_winit_platform = "0.17.0"
pollster = "0.2.5"
wgpu = "0.14.0"
egui_wgpu_backend = "0.21.0"
walkdir = "2.3.2"
toml = "0.7.2"
anyhow = "1.0.69"

[dependencies.serde]
version = "1.0.152"
features = ["derive"]

[features]
debug = ["core/log_opcode"]

[dependencies.shared]
path = "../shared"
[dependencies.core]
path = "../core"
[dependencies.lcd]
path = "../lcd"
[dependencies.bus]
path = "../bus"
[dependencies.mem]
path = "../mem"
[dependencies.dbg]
path = "../dbg"
