[package]
name = "dbg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
egui_extras = "0.21.0"

[dependencies.core]
path = "../core"

[dependencies.shared]
path = "../shared"
